- Makefile
- README.md
- ci-values.yaml
- java/Chart.yaml
- java/templates/deployment.yaml
The environment config didn't actually work - it was setup to work like ConfigMap syntax.
> Fix environment config

- java/Chart.yaml
- java/templates/NOTES.txt
It gives useful output which you can easily copy paste after installing the chart.
Can be tuned per chart, but should use this as a base
> Add standard NOTES.txt

- java/templates/bin/_dns-register.tpl
- java/templates/dns-configmap.yaml
- java/templates/dns.yaml
Missing files from last PR......oops!
https://github.com/hmcts/chart-java/pull/27
> Add DNS support - add missing dns files

- Makefile
- README.md
- ci-values.yaml
- java/Chart.yaml
- java/templates/deployment.yaml
> Mount keyvaults as flexvolumes

- README.md
- ci-values.yaml
- java/Chart.yaml
- java/templates/deployment.yaml
- java/values.yaml
Added Instrumentation key to chart as a variable .
https://tools.hmcts.net/jira/browse/RPE-879
Added Instrumentation key to chart as a variable
``` (remove backslash and this comment when copy pasting)
[ ] Yes
[x] No
```
> Added Instrumentation Key for chart as a variable

- README.md
- ci-values.yaml
- java/Chart.yaml
- java/templates/deployment.yaml
Add secret reference
Use /mnt/secrets mount point for keyvault secrets
> Flexvolumes updates

- java/Chart.yaml
- java/templates/deployment.yaml
> Exclude environment suffix also for resource group.

- java/Chart.yaml
- java/templates/deployment.yaml
Allows container (non-root) user to read the mounted volumes
```
[ ] Yes
[x] No
```
> Update fsGroup to match runAs user group.

- java/Chart.yaml
- java/templates/deployment.yaml
> Move security context to the right level

- ci-values.yaml
- java/Chart.yaml
- java/templates/deployment.yaml
- java/values.yaml
Add inter-pod anti-affinity
```
[ ] Yes
[x ] No
```
> add inter-pod anti-affinity

- README.md
README update - to include registerAdditionalDns details.
```
[ ] Yes
[x] No
```
> Add missing registerAdditionalDns details to readme

- java/Chart.yaml
- java/templates/deployment.yaml
this attribute should be at the container level: https://kubernetes.io/docs/tasks/configure-pod-container/security-context
```
[ ] Yes
[x] No
```
> move allowPrivilegeEscalation to correct location

- README.md
- java/Chart.yaml
- java/templates/pdb.yaml
- java/values.yaml
Adding Pod Disruption Budgets (PDB) to Java Chart
https://tools.hmcts.net/jira/browse/RPE-1014
Adding Pod Disruption Budgets (PDB) to Java Chart
```
[ ] Yes
[x] No
```
> Adding Pod Disruption Budgets (PDB) to Java Chart

- java/values.yaml
https://tools.hmcts.net/jira/browse/RPE-1034
Disable Postgresql by default
```
[ ] Yes
[x ] No
```
> disable postgres by default

- README.md
- ci-values.yaml
- java/Chart.yaml
- java/templates/_helpers.tpl
NA
Adding option to disable individual secrets to be able to override default chart behaviour
```
[ ] Yes
[x] No
```
> Adding option to disable individual secrets 

- README.md
- ci-values.yaml
- java/Chart.yaml
- java/templates/_helpers.tpl
- java/templates/deployment.yaml
Added tpl for environment value to be able to template the values.
https://tools.hmcts.net/jira/browse/RPE-914
Added tpl for environment value to be able to template the values.
This will enable us to template the values in env.
```
[ ] Yes
[ ] No
```
> Added tpl for environment value to be able to template the values.

- ci-values.yaml
- java/Chart.yaml
- java/templates/_helpers.tpl
NA
Supporting boolean without quotes for env vars
```
[ ] Yes
[x] No
```
> Supporting boolean without quotes for env vars

- README.md
update README to include a section for Postgresql
update README to include a section for Postgresql
```
[ ] Yes
[x ] No
```
> add Postgresql section to README

- README.md
fix broken readme file
fix broken readme file
```
[ ] Yes
[x ] No
```
> move Postgresql section to code block in README

- java/Chart.yaml
- java/requirements.yaml
Upgrading postgresql chart as there is a breaking change causing postgres pods to fail.
```
[ ] Yes
[x] No
```
> Upgrading postgresql chart

- azure-pipelines.yaml
- java/Chart.yaml
- java/templates/deployment.yaml
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/81
Set `revisionHistoryLimit: 0` as we are not using history to perform rollbacks.
```
[ ] Yes
[x] No
```
> disable revision history

- README.md
- java/Chart.yaml
- java/templates/deployment.yaml
[AB#126](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/126)
Allow pod identity configuration
```
[ ] Yes
[ ] No
```
> Add pod identity support

- README.md
- java/Chart.yaml
- java/templates/deployment.yaml
[AB#126](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/126)
Ugh missed this in my last PR
```
[ ] Yes
[ ] No
```
> Fix AAD pod id binding

- ci-values.yaml
- java/Chart.yaml
- java/templates/_helpers.tpl
- java/templates/configmap.yaml
- java/templates/deployment.yaml
- java/templates/ingress.yaml
- java/templates/pdb.yaml
- java/templates/service.yaml
- java/values.yaml
Use label and annotation helpers like in chart-nodejs
```
[ ] Yes
[ ] No
```
> Add prometheus annotations to chart

- README.md
- ci-values.yaml
- java/Chart.yaml
- java/templates/ingress.yaml
It will be helpful to remove duplication in Micro service charts and also help making product chart ingress dynamic ( example - CCD )
```
[ ] Yes
[x] No
```
> Adding templating for ingress

- java/Chart.yaml
- java/requirements.yaml
- java/values.yaml
> Bumping to latest postgresql chart

- README.md
- java/Chart.yaml
- java/templates/_helpers.tpl
> Adding tpl support for releasenameoverride

- java/Chart.yaml
- java/values.yaml
> Fix prod limits. Bump version

- README.md
- ci-values.yaml
- java/Chart.yaml
- java/templates/deployment.yaml
See https://github.com/Azure/kubernetes-keyvault-flexvol/pull/128 for background
> Remove resource group and subscription ID

- java/Chart.yaml
- java/templates/deployment.yaml
> Fixing new line issue in case of PRs

- java/Chart.yaml
- java/requirements.yaml
- java/values.yaml
> Add smoke + functional test jobs

- Makefile
- java/Chart.yaml
- java/requirements.yaml
- java/values.yaml
> Test jobs clean up

- java/Chart.yaml
- java/requirements.yaml
- java/values.yaml
> Update jobs names for dns compatibility

- Makefile
- ci-tests-values.yaml
- java/Chart.yaml
- java/requirements.yaml
- java/templates/_helpers.tpl
- java/templates/deployment-tests.yaml
- java/values.yaml
> Add functional/smoke test pods

- ci-tests-values.yaml
- java/Chart.yaml
- java/templates/_helpers.tpl
> Add tests env

- ci-tests-values.yaml
- java/Chart.yaml
- java/templates/deployment-tests.yaml
> Fix tests aad identity

- java/Chart.yaml
- java/templates/_helpers.tpl
- java/templates/deployment-tests.yaml
> Add test metadata template. Remove hook

- java/Chart.yaml
- java/templates/deployment-tests.yaml
> Fix tests definition indentation

- README.md
- ci-tests-values.yaml
- java/Chart.yaml
- java/requirements.yaml
- java/templates/_helpers.tpl
- java/templates/deployment-tests.yaml
- java/values.yaml
> Tests config fixes

- .gitignore
- README.md
- java/Chart.yaml
- java/templates/_helpers.tpl
- java/templates/deployment-tests.yaml
- java/values.yaml
> Smoke / functional testing improvements

- azure-pipelines.yaml
- java/Chart.yaml
[AB#715](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/715)
No changes here, just testing the helm 3 updates in the library
```
[ ] Yes
[ ] No
```
> Release with helm 3

- java/Chart.yaml
- java/templates/deployment.yaml
- java/values.yaml
> Making imagepullpolicy configurable

- ci-tests-values.yaml
- java/Chart.yaml
- java/templates/_helpers.tpl
- java/values.yaml
[[AB#720](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/720)]
```
[ ] Yes
[x] No
```
> Update tests to use new sa

- java/Chart.yaml
- java/templates/service.yaml
- java/values.yaml
SIDM-3485 - IDAM Session Affinity
https://tools.hmcts.net/jira/browse/SIDM-3485
IDAM Session Affinity
```
[ ] Yes
[x] No
```
> add option for idam session affinity

- ci-values.yaml
- java/Chart.yaml
- java/templates/tests/test-service.yaml
add resource request to test-service
```
[ ] Yes
[x ] No
```
> add resource request

- README.md
> Removed appinsightskey and updated changes for readiness

- java/requirements.lock
- java/values.yaml
> Enable use interpod antiaffinity by default

- java/values.yaml
[AB#936]
```
[ ] Yes
[x] No
```
> Update default dns options

- java/Chart.yaml
> Fix release name override.

- java/Chart.yaml
> Upgrade library for fixing secretproviderclass issue on multiple keyvaults

- java/Chart.yaml
> Upgrade Library

- README.md
- java/Chart.yaml
- java/values.yaml
> upgrading library

- java/Chart.yaml
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> Upgrade Library to Version 0.5.8

- java/Chart.yaml
> upgrading chart library to 0.5.9

- java/templates/secretproviderclass-tests.yaml
> DTSPO-2939 Fix to create secretproviderclass-tests

- java/Chart.yaml
- java/templates/secretproviderclass-tests.yaml
> Dtspo 2939 secretproviderclass tests fix

- java/Chart.yaml
- java/templates/ingress.yaml
(https://tools.hmcts.net/jira/browse/DTSPO-6533)
Upgrade release version of chart-library
Upgrade ingress version
```
[ ] Yes
[x] No
```
> DTSPO-6533 Upgrade ingress version to v1 and add startup probes

- java/values.yaml
I saw apps starting in less than 10 seconds let's not delay too long
> Reduce startup delay more

- Makefile
- README.md
- azure-pipelines.yaml
- java/Chart.yaml
- java/templates/secretproviderclass.yaml
Update chart-library to v1.0.4
Update makefile for local testing
Update readme to reflect updated AKS cluster to use
> DTSPO-6480 - update library to v1.0.4

- java/Chart.yaml
So Camunda can use the latest chart version without breaking.
```
[ ] Yes
[x] No
```
> DTSPO-6156 Re-add annotations for traefik v1

- java/Chart.yaml
Upgrade the library version from 1.0.6 to 1.0.7
```
[ ] Yes
[ x ] No
```
> Allow replacing <ENV> in secret names

- java/Chart.yaml
> Upgrading postgresql chart to latest 11 version

- java/Chart.yaml
https://github.com/hmcts/chart-library/releases/tag/1.1.2
```
[ ] Yes
[x] No
```
> Upgrade chart-library

- java/Chart.yaml
https://github.com/hmcts/chart-library/releases/tag/1.1.3-alpha - to test with plum the chart-library changes
```
[ ] Yes
[ ] No
```
> Bump to alpha chart-library version

- ci-values.yaml
- java/Chart.yaml
VIH-9521 - Bump Library Chart
VIH-9521 - Bump Library Chart
```
[ ] Yes
[ x ] No
```
> VIH-9521 - Bump Library Chart

- java/Chart.yaml
> DTSPO-12023 API update

- java/Chart.yaml
> Upgrade library to fix hpa issue

- ci-values.yaml
- java/Chart.yaml
- java/templates/deployment.yaml
Testing with new library version to update template and deployment version upgrades
```
[ ] Yes
[ ] No
```
> Bump chart-library version

- java/Chart.yaml
Upgrading chart-library for workload identity secretproviderclass changes
```
[ ] Yes
[ ] No
```
> Upgrade chart-library version to 2.0.13

- ci-values.yaml
- java/Chart.yaml
- java/templates/secretproviderclass.yaml
- java/values.yaml
> enable wl identity by default

- java/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14559
Update library to 2.0.21
Includes ability to add annotations on ingress
Required to allow bypassing of external-dns
> DTSPO-14559 - Update library

- java/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPO-14559
Bump library to 2.0.22
> DTSPO-14559 - Bump library to 2.0.22
